export const CREATE_GENERATOR_PACKAGE = "CREATE_GENERATOR_PACKAGE"
export const ADD_SCHEMA_TO_GENERATOR = "ADD_SCHEMA_TO_GENERATOR"
export const GENERATE_CODE = "GENERATE_CODE"

export const GET_APPLICATION = "GET_APPLICATION"
export const CREATE_APPLICATION = "CREATE_APPLICATION"
export const DELETE_APPLICATION = "DELETE_APPLICATION"

export const GET_PROJECT = "GET_PROJECT"
export const CREATE_PROJECT = "CREATE_PROJECT"
export const DELETE_PROJECT = "DELETE_PROJECT"

export const GET_SCHEMA = "GET_SCHEMA"
export const CREATE_SCHEMA = "CREATE_SCHEMA"
export const DELETE_SCHEMA = "DELETE_SCHEMA"

export const GET_ATTRIBUTE = "GET_ATTRIBUTE"
export const CREATE_ATTRIBUTE = "CREATE_ATTRIBUTE"
export const DELETE_ATTRIBUTE = "DELETE_ATTRIBUTE"

export const LOGIN = "LOGIN"
export const LOGOUT = "LOGOUT"